"""Shared types. The seam between every layer of the system.

Import from here, not from the submodules, so that a future reshuffle of the
package internals does not ripple through the codebase.
"""

from crewops.contracts.evidence import (
    Abstention,
    AbstentionReason,
    Citation,
    Confidence,
    Fact,
    FactUnit,
    FactValue,
    Provenance,
    Table,
    Timings,
    ToolEnvelope,
    TraceStep,
    UnattestedAtom,
    VerificationReport,
    VerificationStatus,
)
from crewops.contracts.ops import (
    Alert,
    CostBreakdown,
    CostLine,
    CoverKind,
    CoverOption,
    DownstreamRisk,
    FlightRef,
    ImpactReport,
    Recommendation,
    RiskSeverity,
    Watchlist,
)
from crewops.contracts.reply import AnswerMode, Reply, ReplyKind, Tier
from crewops.contracts.rules import (
    ALL_RULE_IDS,
    DayLegality,
    LegalityReport,
    RuleId,
    RuleTrace,
    Verdict,
)
from crewops.contracts.stream import (
    AbstainEvent,
    ChatRequest,
    DoneEvent,
    ErrorEvent,
    EventType,
    PlanEvent,
    ReplyEvent,
    RunStartedEvent,
    StreamEvent,
    TokenEvent,
    ToolCallEvent,
    ToolResultEvent,
    TraceEvent,
    VerificationEvent,
    VerifyingEvent,
)
from crewops.contracts.tools import RETRIEVAL_ONLY, TOOL_NAMES, ToolSurface

__all__ = [
    "ALL_RULE_IDS",
    "RETRIEVAL_ONLY",
    "TOOL_NAMES",
    "AbstainEvent",
    "Abstention",
    "AbstentionReason",
    "Alert",
    "AnswerMode",
    "ChatRequest",
    "Citation",
    "Confidence",
    "CostBreakdown",
    "CostLine",
    "CoverKind",
    "CoverOption",
    "DayLegality",
    "DoneEvent",
    "DownstreamRisk",
    "ErrorEvent",
    "EventType",
    "Fact",
    "FactUnit",
    "FactValue",
    "FlightRef",
    "ImpactReport",
    "LegalityReport",
    "PlanEvent",
    "Provenance",
    "Recommendation",
    "Reply",
    "ReplyEvent",
    "ReplyKind",
    "RiskSeverity",
    "RuleId",
    "RuleTrace",
    "RunStartedEvent",
    "StreamEvent",
    "Table",
    "Tier",
    "Timings",
    "TokenEvent",
    "ToolCallEvent",
    "ToolEnvelope",
    "ToolResultEvent",
    "ToolSurface",
    "TraceEvent",
    "TraceStep",
    "UnattestedAtom",
    "Verdict",
    "VerificationEvent",
    "VerificationReport",
    "VerificationStatus",
    "VerifyingEvent",
    "Watchlist",
]
