"""Typed records, the loader, the immutable world and its overlay.

No language model is reachable from this package. It reads the shipped dataset
and indexes it. It computes nothing that a rule depends on: that is
`crewops.rules`.
"""

from crewops.domain.loader import DATA_DIR, DATA_DIR_ENV, RawDataset, load_raw, read_json
from crewops.domain.models import (
    CABIN_RANKS,
    COVER_PAIRING_ID,
    PILOT_RANKS,
    AircraftType,
    Certification,
    CertType,
    Costs,
    Crew,
    CrewStatus,
    DayHistory,
    DutyClock,
    FlaggedException,
    Flight,
    OnCallWindow,
    Pairing,
    PairingCrew,
    PairingDay,
    Rank,
    Reserve,
    RiskSignal,
    Rosters,
    RuleBook,
    RuleDefinition,
    WeekDuty,
)
from crewops.domain.time_utils import (
    UTC_FORMAT,
    add_hours,
    at_clock,
    date_range,
    format_duration,
    format_margin,
    format_utc,
    hours_between,
    parse_date,
    parse_utc,
    window_dates,
)
from crewops.domain.world import ClockKind, WorldOverlay, WorldState, load_world

__all__ = [
    "CABIN_RANKS",
    "COVER_PAIRING_ID",
    "DATA_DIR",
    "DATA_DIR_ENV",
    "PILOT_RANKS",
    "UTC_FORMAT",
    "AircraftType",
    "CertType",
    "Certification",
    "ClockKind",
    "Costs",
    "Crew",
    "CrewStatus",
    "DayHistory",
    "DutyClock",
    "FlaggedException",
    "Flight",
    "OnCallWindow",
    "Pairing",
    "PairingCrew",
    "PairingDay",
    "Rank",
    "RawDataset",
    "Reserve",
    "RiskSignal",
    "Rosters",
    "RuleBook",
    "RuleDefinition",
    "WeekDuty",
    "WorldOverlay",
    "WorldState",
    "add_hours",
    "at_clock",
    "date_range",
    "format_duration",
    "format_margin",
    "format_utc",
    "hours_between",
    "load_raw",
    "load_world",
    "parse_date",
    "parse_utc",
    "read_json",
    "window_dates",
]
